# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('pnt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.Restaurant')),
            ],
        ),
    ]
